// <auto-generated />
#nullable disable

namespace Project.Persistance.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Project.Core.Entities.Identities.Permission", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Category")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Category");

                b.HasIndex("NormalizedName")
                    .IsUnique();

                b.ToTable("Permissions", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedByIp")
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("datetime2");

                b.Property<string>("ReplacedByToken")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("RevokedByIp")
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("ExpiresAt");

                b.HasIndex("Token")
                    .IsUnique();

                b.HasIndex("UserId");

                b.ToTable("RefreshTokens", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.Role", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsSystemRole")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("NormalizedName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique();

                b.ToTable("Roles", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.RolePermission", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("AssignedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("PermissionId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PermissionId");

                b.HasIndex("RoleId", "PermissionId")
                    .IsUnique();

                b.ToTable("RolePermissions", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DeletedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("FirstName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<bool>("IsLocked")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.Property<string>("LastLoginIp")
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<string>("LastName")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("LastPasswordChangedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("LockoutEnd")
                    .HasColumnType("datetime2");

                b.Property<string>("NormalizedEmail")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("bit");

                b.Property<string>("ProfileImageUrl")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("SecurityStamp")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("bit");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("IsDeleted");

                b.HasIndex("NormalizedEmail")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.UserLoginHistory", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("AttemptedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("FailureReason")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("IpAddress")
                    .IsRequired()
                    .HasMaxLength(45)
                    .HasColumnType("nvarchar(45)");

                b.Property<bool>("IsSuccessful")
                    .HasColumnType("bit");

                b.Property<string>("UserAgent")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("AttemptedAt");

                b.HasIndex("IsSuccessful");

                b.HasIndex("UserId");

                b.ToTable("UserLoginHistories", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.UserRole", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("AssignedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("RoleId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.HasIndex("UserId", "RoleId")
                    .IsUnique();

                b.ToTable("UserRoles", (string)null);
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.RefreshToken", b =>
            {
                b.HasOne("Project.Core.Entities.Identities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.RolePermission", b =>
            {
                b.HasOne("Project.Core.Entities.Identities.Permission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Project.Core.Entities.Identities.Role", "Role")
                    .WithMany("Permissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Permission");

                b.Navigation("Role");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.UserLoginHistory", b =>
            {
                b.HasOne("Project.Core.Entities.Identities.User", "User")
                    .WithMany("LoginHistory")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.UserRole", b =>
            {
                b.HasOne("Project.Core.Entities.Identities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Project.Core.Entities.Identities.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.Permission", b =>
            {
                b.Navigation("RolePermissions");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.Role", b =>
            {
                b.Navigation("Permissions");

                b.Navigation("UserRoles");
            });

        modelBuilder.Entity("Project.Core.Entities.Identities.User", b =>
            {
                b.Navigation("LoginHistory");

                b.Navigation("RefreshTokens");

                b.Navigation("UserRoles");
            });
#pragma warning restore 612, 618
    }
}
